# -*- coding: utf-8 -*-
# 中→英 译文对照（与 prose_manifest.json 顺序一一对应，gen_en.py 会校验）
PAIRS = [
("title: SW-Markdown文档阅读工具", "title: SW-Markdown Document Reader Tool"),
("# SW-Markdown文档阅读工具", "# SW-Markdown Document Reader Tool"),
("### 介绍", "### Introduction"),
("`Markdown`文件是一个简单的文本型文档, 后缀为`.md`，用`Markdown工具`可以渲染和格式化内容。", "A `Markdown` file is a simple text document with the `.md` extension; a `Markdown tool` renders and formats its content."),
("这是一个Markdown工具，打开一个Markdown文本文件，可以预览渲染后`Markdown`文件内容，也支持`LaTex数学公式`和`mermaid图形`的渲染。", "This is a Markdown tool: open a Markdown text file to preview the rendered content. It also renders `LaTeX math formulas` and `mermaid diagrams`."),
("### 工具安装", "### Installation"),
("拷贝下面的文件和目录到一个安装目标路径下，即可完成，开始使用。比如D:\\md_tool\\ 目录下。", "Copy the files and directories below to an installation target path, e.g. the `D:\\md_tool\\` directory, and you are ready to use it."),
("这个工具是一个本地网页工具，用浏览器打开 `markdown_katex_tool.html` 这个web工具页面。然后在页面上点击按钮，打开电脑上的一个`.md`文件，进行预览查看。", "This tool is a local web page: open `markdown_katex_tool.html` in a browser, click the button on the page, pick a `.md` file on your computer, and preview it."),
("**快捷键**", "**Shortcuts**"),
("`Ctrl`+`P` 打印预览区内容，（Windows系统）在打印对话框的`更多设置`里，可以选择带有预览`背景`打印,另外可以选择打印到打印机，或者打印到一个PDF文件（Windows默认支持打印到PDF文件）；", "`Ctrl`+`P` prints the preview area content. On Windows, in the `More settings` of the print dialog you can choose to print with the preview `background`, print to a printer, or print to a PDF file (Windows supports printing to PDF by default)."),
("`Ctrl`+`S` 打开一个新的页面显示预览区内容。", "`Ctrl`+`S` opens a new page showing the preview area content."),
("点击`打印按钮`，也可以打印预览区内容，等效与快捷键`Ctrl`+`P`。", "Clicking the `Print button` also prints the preview area content, equivalent to `Ctrl`+`P`."),
("`Markdown`文件的例子：", "An example `Markdown` file:"),
("# 编写一个简单的Markdown文件", "# Writing a Simple Markdown File"),
("### 编写Markdown文件的软件工具", "### Tools for Writing Markdown Files"),
("用任何一个纯文本编辑工具，就可以写`Markdown`文件，比如 `记事本`，`notepad` 等。不推荐用格式化的编辑软件（word/WPS），因为它的文件内容格式不是纯文本，markdown工具无法识别它的内容。保存文件名的后缀用`.md`，预览可以用本工具(`SW-Markdown文档阅读工具`)进行渲染查看。", "Any plain-text editor can write `Markdown` files, e.g. `Notepad`. Formatted editors (Word/WPS) are not recommended because their content is not plain text and Markdown tools cannot read it. Save files with the `.md` extension and preview them with this tool (`SW-Markdown Document Reader Tool`)."),
("如果想边写边看效果，实时看效果，推荐用代码编辑软件 `VSCode` + 插件 `Markdown Preview Enhanced` 。", "For live preview while writing, use `VSCode` with the `Markdown Preview Enhanced` extension."),
("### Markdown简单语法", "### Basic Markdown Syntax"),
("`标题`(以#,##,...,######开头+空格+标题名称且支持六个级并且要独占一行), `围栏`(放在两个三联反引号\\`\\`\\`之内)，`关键字`(放在两个单联反引号\\`之内)，`加粗`（放在两个双联星号\\*\\*之内），`斜体`（放在两个单联星号\\*之内），`分割线`（空行开头放一个三联短线---），`段落`（前后各有一个空行分割），`缩进围栏`（前后各有一个空行分割并且内容每行都缩进4个空格），`表格`（用竖线|表示列并用它有规则地围起来就表示表格），`引用`（用每行开头加`>`和`空格`），等等。", "`Headings` (start a line with #, ##, …, up to ######, followed by a space and the heading text; six levels, each on its own line), `fenced blocks` (between two triple backticks \\`\\`\\`), `inline code` (between two single backticks \\`), `bold` (between two pairs of asterisks \\*\\*), `italic` (between single asterisks \\*), `horizontal rules` (a line starting with three dashes ---), `paragraphs` (separated by blank lines), `indented fences` (surrounded by blank lines, each content line indented by 4 spaces), `tables` (use vertical bars | to define columns and surround the content with them), `blockquotes` (each line starts with `>` and a space), etc."),
("块级`围栏`内可以放各种`文本`，`代码`，以及要解析和渲染的`LaTex/katex数学公式`或者`mermaid图形语句`，等等。", "A block-level `fenced block` can contain various `text`, `code`, and `LaTeX/KaTeX math formulas` or `mermaid diagram statements` to be parsed and rendered, etc."),
("Markdown文件的文本内容可读性强，简单语法并不影响文本阅读，而且它可以被markdown工具渲染成有格式的文档，也很容易将渲染后的HTML的效果转换为PDF文档。", "Markdown content is highly readable; the simple syntax does not interfere with reading. Markdown tools render it into formatted documents, and the rendered HTML can easily be converted to PDF."),
("### 围栏", "### Fenced Blocks"),
("一般用两个三联反引号\\`\\`\\`，中间方内容。围栏前后要有空行。或者用缩进围栏方式，将内容的每行缩进4个空格。", "Usually wrap content between two triple backticks \\`\\`\\`, with a blank line before and after the fence. Alternatively use an indented fence by indenting each content line by 4 spaces."),
("Markdown语法如下：", "The Markdown syntax is as follows:"),
("渲染效果：", "Rendered result:"),
("如果内容为编程语言代码或特殊语言，在第一个三联反引号\\`\\`\\`后面可以跟一个语言名称，比如html。常用的编程语言（html/javascript/c/c++/perl/python等）都可以做语法加亮(highlight)。", "If the content is programming code or a special language, you can put a language name right after the opening triple backtick \\`\\`\\`, e.g. html. Common programming languages (html/javascript/c/c++/perl/python, etc.) support syntax highlighting."),
("### Markdown的表格用法", "### Markdown Tables"),
("用`|`围成表格。每行为表格一行；每列用一个`|`，行头以`|`开始，行尾以`|`结束。2列每行有三个`|`，3列每行有四个`|`，以此类推。第一行为表格头。第二行为表格对齐格式，用三联短线-表示普通格式表头居中且其他行左对齐，例如`---`；用冒号+三联短线表示左对齐，例如`:---`；用三联短线+冒号表示右对齐，例如`---:`；用冒号+三联短线+冒号表示居中对齐，例如`:---:`；", "Surround a table with `|`. Each line is a row; columns are separated by `|`, with rows starting and ending with `|`. A 2-column table has three `|` per row, a 3-column table has four, and so on. The first row is the header. The second row defines alignment: `---` means the header is centered and other rows left-aligned; `:---` left-aligned; `---:` right-aligned; `:---:` centered."),
("| Markdown\t| HTML\t| 呈现的输出| ", "| Markdown\t| HTML\t| Rendered Output| "),
("| `# 一级标题`\t| `<h1>一级标题</h1>`\t| <p style=\"font-size:2.0rem; font-weight: bold;\">一级标题</p> |", "| `# Heading 1`\t| `<h1>Heading 1</h1>`\t| <p style=\"font-size:2.0rem; font-weight: bold;\">Heading 1</p> |"),
("| `## 二级标题`\t| `<h2>二级标题</h2>`\t| <p style=\"font-size:1.8rem; font-weight: bold;\">二级标题</p> |", "| `## Heading 2`\t| `<h2>Heading 2</h2>`\t| <p style=\"font-size:1.8rem; font-weight: bold;\">Heading 2</p> |"),
("| `### 三级标题`\t| `<h3>三级标题</h3>`\t| <p style=\"font-size:1.6rem; font-weight: bold;\">三级标题</p> |", "| `### Heading 3`\t| `<h3>Heading 3</h3>`\t| <p style=\"font-size:1.6rem; font-weight: bold;\">Heading 3</p> |"),
("| `#### 四级标题`\t| `<h4>四级标题</h4>`\t| <p style=\"font-size:1.4rem; font-weight: bold;\">四级标题</p> |", "| `#### Heading 4`\t| `<h4>Heading 4</h4>`\t| <p style=\"font-size:1.4rem; font-weight: bold;\">Heading 4</p> |"),
("| `##### 五级标题`\t| `<h5>五级标题</h5>`\t| <p style=\"font-size:1.2rem; font-weight: bold;\">五级标题</p> |", "| `##### Heading 5`\t| `<h5>Heading 5</h5>`\t| <p style=\"font-size:1.2rem; font-weight: bold;\">Heading 5</p> |"),
("| `###### 六级标题`\t| `<h6>六级标题</h6>`\t| <p style=\"font-size:1.0rem; font-weight: bold;\">六级标题</p> |", "| `###### Heading 6`\t| `<h6>Heading 6</h6>`\t| <p style=\"font-size:1.0rem; font-weight: bold;\">Heading 6</p> |"),
("**右对齐**", "**Right-aligned**"),
("| 名称 | 内容 |", "| Name | Content |"),
("| 短名 | md |", "| Short name | md |"),
("| Markdown文件名 | markdown_katex_tool.html\t|", "| Markdown file name | markdown_katex_tool.html\t|"),
("**居中对齐**", "**Center-aligned**"),
("| 名称\t| 内容\t|", "| Name\t| Content\t|"),
("| 短名\t| md\t|", "| Short name\t| md\t|"),
("### 引用用法", "### Blockquotes"),
("每行用`< `开头。示例：", "Start each line with `< ` (a greater-than sign and a space). Example:"),
("> 更多数学公式用法参考LaTex或katex官方相关文档。", "> For more math formula usage, refer to the official LaTeX or KaTeX documentation."),
("> 更多帮助，请查看`Markdown`帮助文档：https://markdown.cn/docs/intro 。", "> For more help, see the `Markdown` documentation: https://markdown.cn/docs/intro ."),
("> 基本语法文档： https://markdown.cn/docs/tutorial-basics/basic-syntax 。", "> Basic syntax documentation: https://markdown.cn/docs/tutorial-basics/basic-syntax ."),
("> MARKDOWN 中文教程 - markdown.cn [基本语法](https://markdown.cn/docs/tutorial-basics/basic-syntax)  |  [扩展语法](https://markdown.cn/docs/tutorial-basics/extended-syntax) ", "> MARKDOWN tutorial - markdown.cn [Basic syntax](https://markdown.cn/docs/tutorial-basics/basic-syntax)  |  [Extended syntax](https://markdown.cn/docs/tutorial-basics/extended-syntax) "),
("标题", "Headings"),
("|Markdown\t|HTML\t|呈现的输出|", "|Markdown\t|HTML\t|Rendered Output|"),
("|# 一级标题\t|`<h1>` 一级标题`</h1>`\t|<h1> 一级标题</h1>|", "|# Heading 1\t|`<h1>` Heading 1`</h1>`\t|<h1> Heading 1</h1>|"),
("|## 二级标题\t|`<h2>`二级标题`</h2>`|<h2>二级标题</h2>|", "|## Heading 2\t|`<h2>`Heading 2`</h2>`|<h2>Heading 2</h2>|"),
("|### 三级标题\t|`<h3>`三级标题`</h3>`\t|<h3>三级标题</h3>|", "|### Heading 3\t|`<h3>`Heading 3`</h3>`\t|<h3>Heading 3</h3>|"),
("|#### 四级标题\t|`<h4>`四级标题`</h4>`\t|<h4>四级标题</h4>|", "|#### Heading 4\t|`<h4>`Heading 4`</h4>`\t|<h4>Heading 4</h4>|"),
("|##### 五级标题\t|`<h5>`五级标题`</h5>`\t|<h5>五级标题</h5>|", "|##### Heading 5\t|`<h5>`Heading 5`</h5>`\t|<h5>Heading 5</h5>|"),
("|###### 六级标题\t|`<h6>`六级标题`</h6>`\t|<h6>六级标题</h6>|", "|###### Heading 6\t|`<h6>`Heading 6`</h6>`\t|<h6>Heading 6</h6>|"),
("段落", "Paragraphs"),
("要创建段落，请使用空行分隔一行或多行文本。", "To create paragraphs, separate one or more lines of text with a blank line."),
("|我真的很喜欢使用<br>Markdown。<br><br>想从现在开始使用它来格式<br>化我所有的文档。\t|`<p>`我真的很喜欢使用<br>Markdown。`</p>`<br><br>`<p>`我想从现在开始使用它来格式<br>化我所有的文档。`</p>`\t|<p>我真的很喜欢使用<br>Markdown。</p><br><p>我想从现在开始使用它来格式<br>化我所有的文档。</p>|", "|I really like using<br>Markdown.<br><br>I think I'll use it to format<br>all of my documents from now on.\t|`<p>`I really like using<br>Markdown.`</p>`<br><br>`<p>`I think I'll use it to format<br>all of my documents from now on.`</p>`\t|<p>I really like using<br>Markdown.</p><br><p>I think I'll use it to format<br>all of my documents from now on.</p>|"),
("换行", "Line Breaks"),
("要创建换行或新行 (`<br>`)，请使用两个或更多空格结束一行，然后键入回车。", "To create a line break or new line (`<br>`), end a line with two or more spaces, then press Enter."),
("|这是第一行。&nbsp;&nbsp;<br>这是第二行。\t|`<p>`这是第一行。`<br>`<br>这是第二行。`</p>`\t|<p>这是第一行。<br>这是第二行。</p>|", "|This is the first line.&nbsp;&nbsp;<br>This is the second line.\t|`<p>`This is the first line.`<br>`<br>This is the second line.`</p>`\t|<p>This is the first line.<br>This is the second line.</p>|"),
("强调", "Emphasis"),
("你可以通过加粗或斜体文本来添加强调。", "You can add emphasis by making text bold or italic."),
("加粗", "Bold"),
("要加粗文本，请在单词或短语前和后添加两个星号或下划线。要加粗单词中间的内容以示强调，请在字母周围添加两个星号，中间不要有空格。", "To bold text, add two asterisks or underscores before and after a word or phrase. To bold the middle of a word for emphasis, add two asterisks around the letters with no spaces."),
("|我非常喜欢 \\*\\*加粗文本\\*\\*。\t|我非常喜欢 `<strong>`加粗文本`</strong>`。\t|我非常喜欢 <strong>加粗文本</strong>。|", "|I just love **bold text**.\t|I just love `<strong>`bold text`</strong>`.\t|I just love <strong>bold text</strong>.|"),
("|我非常喜欢 \\_\\_加粗文本\\_\\_。\t|我非常喜欢 `<strong>`加粗文本`</strong>`。\t|我非常喜欢 <strong>加粗文本</strong>。|", "|I just love __bold text__.\t|I just love `<strong>`bold text`</strong>`.\t|I just love <strong>bold text</strong>.|"),
("斜体", "Italic"),
("要将文本斜体化，请在单词或短语前和后添加一个星号或下划线。要斜体化单词中间的内容以示强调，请在字母周围添加一个星号，中间不要有空格。", "To italicize text, add one asterisk or underscore before and after a word or phrase. To italicize the middle of a word, add one asterisk around the letters with no spaces."),
("|斜体文本是 \\*cat's meow\\*。\t|斜体文本是 `<em>`cat's meow`</em>`。\t|斜体文本是 <em>cat's meow</em>。|", "|Italicized text is the *cat's meow*.\t|Italicized text is the `<em>`cat's meow`</em>`.\t|Italicized text is the <em>cat's meow</em>.|"),
("|斜体文本是 \\_cat's meow\\_。\t|斜体文本是 `<em>`cat's meow`</em>`。\t|斜体文本是 <em>cat's meow</em>。|", "|Italicized text is the _cat's meow_.\t|Italicized text is the `<em>`cat's meow`</em>`.\t|Italicized text is the <em>cat's meow</em>.|"),
("加粗和斜体", "Bold and Italic"),
("要同时使用加粗和斜体来强调文本，请在单词或短语前和后添加三个星号或下划线。要加粗和斜体化单词中间的内容以示强调，请在字母周围添加三个星号，中间不要有空格。", "To emphasize text with both bold and italic, add three asterisks or underscores before and after a word or phrase. To emphasize the middle of a word, add three asterisks around the letters with no spaces."),
("|此文本是 \\*\\*\\*非常重要\\*\\*\\*。\t|此文本是 <em><strong>非常重要</strong></em>。\t|此文本是 <em><strong>非常重要</strong></em>。|", "|This text is ***extremely important***.\t|This text is <em><strong>extremely important</strong></em>.\t|This text is <em><strong>extremely important</strong></em>.|"),
("|此文本是 \\_\\_\\_非常重要\\_\\_\\_。\t|此文本是 <em><strong>非常重要</strong></em>。\t|此文本是 <em><strong>非常重要</strong></em>。|", "|This text is ___extremely important___.\t|This text is <em><strong>extremely important</strong></em>.\t|This text is <em><strong>extremely important</strong></em>.|"),
("|此文本是 \\_\\_\\*非常重要\\*\\_\\_。\t|此文本是 <em><strong>非常重要</strong></em>。\t|此文本是 <em><strong>非常重要</strong></em>。|", "|This text is __*extremely important*__.\t|This text is <em><strong>extremely important</strong></em>.\t|This text is <em><strong>extremely important</strong></em>.|"),
("|此文本是 \\*\\*\\_非常重要\\_\\*\\*。\t|此文本是 <em><strong>非常重要</strong></em>。\t|此文本是 <em><strong>非常重要</strong></em>。|", "|This text is **_extremely important_**.\t|This text is <em><strong>extremely important</strong></em>.\t|This text is <em><strong>extremely important</strong></em>.|"),
("|这是非常\\*\\*\\*非常\\*\\*\\*重要的文本。\t|这是非常<em><strong>非常</strong></em>重要的文本。\t|这是非常<em><strong>非常</strong></em>重要的文本。|", "|This is really ***very*** important text.\t|This is really <em><strong>very</strong></em> important text.\t|This is really <em><strong>very</strong></em> important text.|"),
("引用块", "Blockquotes"),
("要创建引用块，请在段落前添加 `>`。", "To create a blockquote, add a `>` in front of a paragraph."),
("呈现的输出如下所示", "The rendered output is shown below"),
("列表", "Lists"),
("你可以将项目组织成有序列表和无序列表。", "You can organize items into ordered and unordered lists."),
("有序列表", "Ordered Lists"),
("要创建有序列表，请添加带有数字和句号的行项目。数字不必按数字顺序排列，但列表应从数字一开头。", "To create an ordered list, add line items with numbers followed by periods. The numbers do not need to be in numerical order, but the list should start with the number one."),
("|1. 第一项<br>2. 第二项<br>3. 第三项<br>4. 第四项|`<ol>`<br>&nbsp;&nbsp;`<li>`第一项`</li>`<br>&nbsp;&nbsp;`<li>`第二项`</li>`<br>&nbsp;&nbsp;`<li>`第三项`</li>`<br>&nbsp;&nbsp;`<li>`第四项`</li>`<br>`</ol>`|<ol>  <li>第一项</li>  <li>第二项</li>  <li>第三项</li>  <li>第四项</li></ol>|", "|1. First item<br>2. Second item<br>3. Third item<br>4. Fourth item|`<ol>`<br>&nbsp;&nbsp;`<li>`First item`</li>`<br>&nbsp;&nbsp;`<li>`Second item`</li>`<br>&nbsp;&nbsp;`<li>`Third item`</li>`<br>&nbsp;&nbsp;`<li>`Fourth item`</li>`<br>`</ol>`|<ol>  <li>First item</li>  <li>Second item</li>  <li>Third item</li>  <li>Fourth item</li></ol>|"),
("|1. 第一项<br>2. 第二项<br>3. 第三项<br>&nbsp;&nbsp;1. 缩进项<br>&nbsp;&nbsp;2. 缩进项<br>4. 第四项|`<ol>`<br>&nbsp;&nbsp;`<li>`第一项`</li>`<br>&nbsp;&nbsp;`<li>`第二项`</li>`<br>&nbsp;&nbsp;`<li>`第三项<br> &nbsp;&nbsp;&nbsp;&nbsp;`<ol>`<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<li>`缩进项`</li>`<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<li>`缩进项`</li>`<br>&nbsp;&nbsp;&nbsp;&nbsp;`</ol>`<br>&nbsp;&nbsp;`</li>`<br>&nbsp;&nbsp;`<li>`第四项`</li>`<br>`</ol>`|<ol>  <li>第一项</li>  <li>第二项</li>  <li>第三项    <ol>      <li>缩进项</li>      <li>缩进项</li>    </ol>  </li>  <li>第四项</li></ol>|", "|1. First item<br>2. Second item<br>3. Third item<br>&nbsp;&nbsp;1. Indented item<br>&nbsp;&nbsp;2. Indented item<br>4. Fourth item|`<ol>`<br>&nbsp;&nbsp;`<li>`First item`</li>`<br>&nbsp;&nbsp;`<li>`Second item`</li>`<br>&nbsp;&nbsp;`<li>`Third item<br> &nbsp;&nbsp;&nbsp;&nbsp;`<ol>`<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<li>`Indented item`</li>`<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<li>`Indented item`</li>`<br>&nbsp;&nbsp;&nbsp;&nbsp;`</ol>`<br>&nbsp;&nbsp;`</li>`<br>&nbsp;&nbsp;`<li>`Fourth item`</li>`<br>`</ol>`|<ol>  <li>First item</li>  <li>Second item</li>  <li>Third item    <ol>      <li>Indented item</li>      <li>Indented item</li>    </ol>  </li>  <li>Fourth item</li></ol>|"),
("无序列表", "Unordered Lists"),
("要创建无序列表，请在行项目前添加破折号 (-)、星号 (*) 或加号 (+)。缩进一个或多个项目以创建嵌套列表。", "To create an unordered list, add dashes (-), asterisks (*), or plus signs (+) in front of line items. Indent one or more items to create a nested list."),
("|- 第一项<br>- 第二项<br>- 第三项<br>- 第四项|`<ul>`<br>&nbsp;&nbsp;`<li>`第一项`</li>`<br>&nbsp;&nbsp;`<li>`第二项`</li>`<br>&nbsp;&nbsp;`<li>`第三项`</li>`<br>&nbsp;&nbsp;`<li>`第四项`</li>`<br>`</ul>`|<ul>  <li>第一项</li>  <li>第二项</li>  <li>第三项</li>  <li>第四项</li></ul>|", "|- First item<br>- Second item<br>- Third item<br>- Fourth item|`<ul>`<br>&nbsp;&nbsp;`<li>`First item`</li>`<br>&nbsp;&nbsp;`<li>`Second item`</li>`<br>&nbsp;&nbsp;`<li>`Third item`</li>`<br>&nbsp;&nbsp;`<li>`Fourth item`</li>`<br>`</ul>`|<ul>  <li>First item</li>  <li>Second item</li>  <li>Third item</li>  <li>Fourth item</li></ul>|"),
("|* 第一项<br>* 第二项<br>* 第三项<br>* 第四项|`<ul>`<br>&nbsp;&nbsp;`<li>`第一项`</li>`<br>&nbsp;&nbsp;`<li>`第二项`</li>`<br>&nbsp;&nbsp;`<li>`第三项`</li>`<br>&nbsp;&nbsp;`<li>`第四项`</li>`<br>`</ul>`|<ul>  <li>第一项</li>  <li>第二项</li>  <li>第三项</li>  <li>第四项</li></ul>|", "|* First item<br>* Second item<br>* Third item<br>* Fourth item|`<ul>`<br>&nbsp;&nbsp;`<li>`First item`</li>`<br>&nbsp;&nbsp;`<li>`Second item`</li>`<br>&nbsp;&nbsp;`<li>`Third item`</li>`<br>&nbsp;&nbsp;`<li>`Fourth item`</li>`<br>`</ul>`|<ul>  <li>First item</li>  <li>Second item</li>  <li>Third item</li>  <li>Fourth item</li></ul>|"),
("|+ 第一项<br>+ 第二项<br>+ 第三项<br>+ 第四项|`<ul>`<br>&nbsp;&nbsp;`<li>`第一项`</li>`<br>&nbsp;&nbsp;`<li>`第二项`</li>`<br>&nbsp;&nbsp;`<li>`第三项`</li>`<br>&nbsp;&nbsp;`<li>`第四项`</li>`<br>`</ul>`|<ul>  <li>第一项</li>  <li>第二项</li>  <li>第三项</li>  <li>第四项</li></ul>|", "|+ First item<br>+ Second item<br>+ Third item<br>+ Fourth item|`<ul>`<br>&nbsp;&nbsp;`<li>`First item`</li>`<br>&nbsp;&nbsp;`<li>`Second item`</li>`<br>&nbsp;&nbsp;`<li>`Third item`</li>`<br>&nbsp;&nbsp;`<li>`Fourth item`</li>`<br>`</ul>`|<ul>  <li>First item</li>  <li>Second item</li>  <li>Third item</li>  <li>Fourth item</li></ul>|"),
("|- 第一项<br>- 第二项<br>- 第三项<br>&nbsp;&nbsp;&nbsp;&nbsp;- 缩进项<br>&nbsp;&nbsp;&nbsp;&nbsp;- 缩进项<br>- 第四项|`<ul>`<br>&nbsp;&nbsp;`<li>`第一项`</li>`<br>&nbsp;&nbsp;`<li>`第二项`</li>`<br>&nbsp;&nbsp;`<li>`第三项<br>&nbsp;&nbsp;&nbsp;&nbsp;`<ul>`<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<li>`缩进项`</li>`<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<li>`缩进项`</li>`<br>&nbsp;&nbsp;&nbsp;&nbsp;`</ul>`<br>&nbsp;&nbsp;`</li>`<br>&nbsp;&nbsp;`<li>`第四项`</li>`<br>`</ul>`|<ul>  <li>第一项</li>  <li>第二项</li>  <li>第三项    <ul>      <li>缩进项</li>      <li>缩进项</li>    </ul>  </li>  <li>第四项</li></ul>|", "|- First item<br>- Second item<br>- Third item<br>&nbsp;&nbsp;&nbsp;&nbsp;- Indented item<br>&nbsp;&nbsp;&nbsp;&nbsp;- Indented item<br>- Fourth item|`<ul>`<br>&nbsp;&nbsp;`<li>`First item`</li>`<br>&nbsp;&nbsp;`<li>`Second item`</li>`<br>&nbsp;&nbsp;`<li>`Third item<br>&nbsp;&nbsp;&nbsp;&nbsp;`<ul>`<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<li>`Indented item`</li>`<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<li>`Indented item`</li>`<br>&nbsp;&nbsp;&nbsp;&nbsp;`</ul>`<br>&nbsp;&nbsp;`</li>`<br>&nbsp;&nbsp;`<li>`Fourth item`</li>`<br>`</ul>`|<ul>  <li>First item</li>  <li>Second item</li>  <li>Third item    <ul>      <li>Indented item</li>      <li>Indented item</li>    </ul>  </li>  <li>Fourth item</li></ul>|"),
("在列表中添加元素", "Adding Elements in Lists"),
("要在列表中添加另一个元素，同时保留列表的连续性，请将元素缩进四个空格或一个制表符，如下例所示。", "To add another element in a list while keeping the list continuous, indent the element by four spaces or one tab, as in the example below."),
("> 提示", "> Tip"),
("如果事情没有按预期出现，请仔细检查你是否已将列表中的元素缩进了四个空格或一个制表符。", "If things do not appear as expected, double-check that you indented the elements in the list by four spaces or one tab."),
("代码块", "Code Blocks"),
("代码块 通常缩进四个空格或一个制表符。当它们在列表中时，将它们缩进八个空格或两个制表符。", "Code blocks are usually indented by four spaces or one tab. When they are inside a list, indent them by eight spaces or two tabs."),
("**Markdown文档例子**", "**Markdown document example**"),
("比如，新建一个文件`t.md`，它的内容如下。", "For example, create a file `t.md` with the following content."),
("预览效果，如下：", "Preview effect, as follows:"),
("# LaTex数学公式示例", "# LaTeX Math Formula Examples"),
("**LaTex数学公式**", "**LaTeX math formulas**"),
("如果两个单`$`内或两个双`$$`的`LaTex公式`解析不出来，检查公式格式是否正确。对于两个双`$$`的`LaTex公式`解析，可以在开始的`$$`前面一行多加一个回车换行后，再看看是否解决问题。", "If a `LaTeX formula` inside two single `$` or two double `$$` fails to parse, check that the formula format is correct. For formulas inside double `$$`, try adding an extra blank line before the opening `$$` and see whether that fixes the issue."),
("> 关于`latex数学公式`的,请查看`katex`的文档：https://katex.org/docs/supported ，https://katex.org/docs/support_table  。", "> For `LaTeX math formulas`, see the `KaTeX` documentation: https://katex.org/docs/supported , https://katex.org/docs/support_table ."),
("### 行内公式", "### Inline Formulas"),
("牛顿第二定律：$F = ma$，其中 $a$ 是加速度。", "Newton's second law: $F = ma$, where $a$ is the acceleration."),
("这些公式可以写在两个`$`内部，比如`$F = ma$`，`$a$` 。", "These formulas can be written between two `$`, e.g. `$F = ma$`, `$a$`."),
("### 块级公式", "### Block Formulas"),
("还有比较复杂的公式，可以写在两个`$$`内部。", "More complex formulas can be written between two `$$`."),
("比如：", "For example:"),
("效果：", "Result:"),
("也可以将公式放在围栏块标志符\\`\\`\\`，加上katex指出语言类型。", "You can also put formulas inside a fenced block \\`\\`\\` and specify katex as the language."),
("比如，", "For example,"),
("二次方程求根公式：", "Quadratic formula:"),
("### 矩阵乘法", "### Matrix Multiplication"),
("### 表格中的数学公式", "### Math Formulas in Tables"),
("Markdown的表格", "Markdown table"),
("| 符号       | 公式          |", "| Symbol       | Formula          |"),
("| 平均值     | $\\bar{x}$     |", "| Mean     | $\\bar{x}$     |"),
("| 方差       | $\\sigma^2$    |", "| Variance       | $\\sigma^2$    |"),
("### 其它例子", "### More Examples"),
("效果：$A = \\{1,2,3\\}$，$B = \\{x|(x - 1)(x - 2)(x - 3)=0\\}$", "Result: $A = \\{1,2,3\\}$, $B = \\{x|(x - 1)(x - 2)(x - 3)=0\\}$"),
("效果：$A = \\{x|0\\lt 2x - 1\\lt 1\\}$，$B = \\{x|1\\lt 3x + 1\\lt 4\\}$", "Result: $A = \\{x|0\\lt 2x - 1\\lt 1\\}$, $B = \\{x|1\\lt 3x + 1\\lt 4\\}$"),
("# 数学图像的用法", "# Using Math Figures"),
("### 函数图像", "### Function Graphs"),
("#### 函数图-例1", "#### Function Graph - Example 1"),
("画一个指数函数图像 $y=a^x, (0<a<1)$，再画一条直线 $y=1$，相交于点 (0,1)，画出交点 。", "Draw the exponential function $y=a^x, (0<a<1)$, then draw the line $y=1$, which intersects it at (0,1); mark the intersection point."),
("Markdown的数学图像语法， 如下。<br>", "The Markdown syntax for math figures is as follows.<br>"),
("`boundingbox: [-3, 5, 3, -1]`: 定义显示区范围，[left,top,right,bottom] 的坐标的范围。", "`boundingbox: [-3, 5, 3, -1]`: defines the display area, with coordinates in the range [left, top, right, bottom]."),
("`functiongraphs: [...]`: 定义一个或多个函数，放在一个数组[]中 。属性`f`的值是一个数组，[0]定义数学函数，[1]和[2]是函数定义域范围，函数只显示定义域范围内（或者显示区范围内）的函数图像。属性`a`的值是一个字典对象，'name' 可以指定显示函数名称或文本；'label' 可以对'name' 的显示相对位置等进行设置；'dash' 设置函数曲线为虚线，`dash:1` 表示线粗为1。 ", "`functiongraphs: [...]`: defines one or more functions in an array `[]`. The `f` attribute is an array: [0] defines the math function, [1] and [2] are the domain range, and only the part of the graph within the domain (or display area) is shown. The `a` attribute is a dictionary: 'name' sets the displayed function name or text; 'label' configures the relative display position of 'name'; 'dash' makes the curve dashed, with `dash:1` meaning a dash thickness of 1. "),
("`points: [...]`: 定义一个或多个坐标点，放在一个数组[]中 。 每个点由一个数组[]来定义，[0],[1] 参数是点的x,y坐标；[2] 参数是点的名称；[3] 是一个字典对象，属性'pos'定义点名称显示的相对位置。", "`points: [...]`: defines one or more points in an array `[]`. Each point is defined by an array: [0] and [1] are the x, y coordinates; [2] is the point name; [3] is a dictionary whose 'pos' property sets the relative display position of the point name."),
("`texts: [...]`: 定义一个或多个文本字串，放在一个数组[]中 。 每个文本字串由一个数组[]来定义，[0],[1] 参数是文本字串显示起始位置的x,y坐标；[2] 参数是文本字串的内容；[3] 是一个字典对象，属性`useKatex:true`定义文本字串的样式用Katex方式显示，Katex方式可以显示数学公式。", "`texts: [...]`: defines one or more text strings in an array `[]`. Each text string is defined by an array: [0] and [1] are the x, y coordinates of the starting position; [2] is the text content; [3] is a dictionary whose `useKatex:true` property renders the text with KaTeX, which can display math formulas."),
("图像显示， 如下。", "The figure is shown below."),
("#### 函数图-例2", "#### Function Graph - Example 2"),
("画一个指数函数图像 $y=(\\frac{1}{2})^x$ 代表 指数函数 $y=a^x, (0<b<a<1)$ ；", "Draw the exponential function $y=(\\frac{1}{2})^x$ representing $y=a^x, (0<b<a<1)$;"),
("画一个指数函数图像 $y=(\\frac{1}{3})^x$ 代表 指数函数 $y=b^x, (0<b<a<1)$ ；", "Draw the exponential function $y=(\\frac{1}{3})^x$ representing $y=b^x, (0<b<a<1)$;"),
("画一个指数函数图像 $y=3^x$ 代表 指数函数 $y=c^x, (1<d<c)$ ；", "Draw the exponential function $y=3^x$ representing $y=c^x, (1<d<c)$;"),
("画一个指数函数图像 $y=2^x$ 代表 指数函数 $y=d^x, (1<d<c)$ ；", "Draw the exponential function $y=2^x$ representing $y=d^x, (1<d<c)$;"),
("再画一条直线 $x=1$ 。", "Then draw the vertical line $x=1$."),
("#### 函数图-例3", "#### Function Graph - Example 3"),
("#### 函数图-例4", "#### Function Graph - Example 4"),
("#### 函数图-例5", "#### Function Graph - Example 5"),
("#### 函数图-例6", "#### Function Graph - Example 6"),
("#### 函数图-例7", "#### Function Graph - Example 7"),
("#### 函数图-例8", "#### Function Graph - Example 8"),
("#### 函数图-例9", "#### Function Graph - Example 9"),
("#### 函数图-例10", "#### Function Graph - Example 10"),
("#### 函数图-例11", "#### Function Graph - Example 11"),
("#### 函数图-例12", "#### Function Graph - Example 12"),
("#### 函数图-例13", "#### Function Graph - Example 13"),
("#### 函数图-例14", "#### Function Graph - Example 14"),
("#### 函数图-例15", "#### Function Graph - Example 15"),
("#### 函数图-例16", "#### Function Graph - Example 16"),
("#### 函数图-例17", "#### Function Graph - Example 17"),
("#### 函数图-例18", "#### Function Graph - Example 18"),
("### Venn图", "### Venn Diagrams"),
("#### Venn图-例1", "#### Venn Diagram - Example 1"),
("#### Venn图-例2", "#### Venn Diagram - Example 2"),
("#### Venn图-例3", "#### Venn Diagram - Example 3"),
("#### Venn图-例4", "#### Venn Diagram - Example 4"),
("#### Venn图-例5", "#### Venn Diagram - Example 5"),
("# mermaid图形的用法", "# Using mermaid Diagrams"),
("> 查看mermaid的文档：https://mermaid.js.org/intro/ 。", "> See the mermaid documentation: https://mermaid.js.org/intro/ ."),
("**mermaid图形**", "**mermaid diagrams**"),
("`mermaid`插件支持多种图形，包括", "The `mermaid` plugin supports many diagram types, including"),
("等等。", "and more."),
("> 关于`mermaid`的图形语法，请查看`mermaid`的文档：https://mermaid.js.org/intro/ 。", "> For the `mermaid` diagram syntax, see the `mermaid` documentation: https://mermaid.js.org/intro/ ."),
("yaml语法配置参数", "yaml syntax configuration parameters"),
("可以用三联短线内包含配置参数，遵循yaml语法。", "You can include configuration parameters between triple dashes, following yaml syntax."),
("中文文本的标签，两个标签之间要用英文或半角的冒号:分隔，不能用中文冒号作为分隔符。如果一行内显示不下，可以在中文中间加空格，它会自动回行。调整空格的位置，让它显示符合你的审美。", "For labels with Chinese text, separate the two labels with an English (half-width) colon `:`, not a Chinese colon. If a line does not fit, add spaces inside the Chinese text and it will wrap automatically; adjust the spaces to your taste."),
("这里，cScale0 可以设置第一组(section)方框背景色，cScaleLabel0 可以设置该组的文字颜色。", "Here, `cScale0` sets the background color of the first section's boxes, and `cScaleLabel0` sets the text color of that group."),
("fontSize 可以设置 title的字体大小，方框里的字体大小也会随之相应调大或调小。这是缺省显示的字体大小。当显示去扩大或缩小时，文字大小会作等比例缩放。", "`fontSize` sets the font size of the title; the font size inside the boxes scales accordingly. This is the default font size; when the display is zoomed in or out, the text scales proportionally."),
("字体类型可以用fontFamily参数设置。", "The font family can be set with the `fontFamily` parameter."),
("代码：", "Code:"),
("# 页面属性和自定义变量 (Customized variables)", "# Page Properties and Custom Variables"),
("### 使用页面属性值", "### Using Page Property Values"),
("在markdown文章中，可以通过变量来引用属性值。", "In Markdown articles, variables can reference property values."),
("### 定义页面属性", "### Defining Page Properties"),
("Markdown文件页面属性由一种普遍的采用的front matter方式来设置。", "Markdown file page properties are set with the widely used front matter approach."),
("front matter放在文件头部，采用Yaml语法。front matter部分不会被很多Markdown工具渲染（有些工具不支持），它只是会作为文章或页面page的属性被解析。它的格式是用两个三联短线---开头的单独行和中间的yaml格式内容构成，放在文件头部。", "Front matter is placed at the top of the file using yaml syntax. It is not rendered by most Markdown tools (some do not support it); it is parsed as article or page properties. Its format consists of a line starting with two triple dashes `---`, followed by yaml-format content, placed at the top of the file."),
("**Front-matter的规则**", "**Front-matter rules**"),
("博客文章写作时，经常会自动设置文章的front matter 的参数。", "When writing blog articles, the front matter parameters are often set automatically."),
("参数描述layout布局/title标题/date建立日期/updated更新日期/comments开启文章的评论功能/tags标签（不适用于分页）/categories分类（不适用于分页）/permalink覆盖文章网址，等等。", "Parameter description: layout / title / date (creation date) / updated (update date) / comments (enable article comments) / tags (not for pages) / categories (not for pages) / permalink (override the article URL), etc."),
("其中，分类和标签需要区别一下，分类具有顺序性和层次性，也就是说Foo，Bar不等于Bar，Foo；而标签没有顺序和层次。", "Note the difference between categories and tags: categories are ordered and hierarchical — Foo, Bar is not the same as Bar, Foo — while tags have no order or hierarchy."),
("注意：每个冒号后面是有一个空格的。", "Note: each colon is followed by a space."),
("下面是一个常用博客文章的front matter属性。", "Below are the front matter properties of a common blog article."),
("|配置选项|默认值|描述|", "|Option|Default|Description|"),
("| title\t| Markdown 的文件标题\t| 文章标题，强烈建议填写此选项|", "| title\t| Markdown file title\t| Article title; strongly recommended|"),
("| date\t| 文件创建时的日期时间\t| 发布时间，强烈建议填写此选项，且最好保证全局唯一|", "| date\t| Date and time when the file was created\t| Publish date; strongly recommended, ideally globally unique|"),
("| author\t| 根 _config.yml中的 author\t| 文章作者|", "| author\t| author in the root _config.yml\t| Article author|"),
("| tagName\t| 根 _config.yml中的 author\t| 类型为文章，会格式化显示作者、日期、tags。|", "| tagName\t| author in the root _config.yml\t| Article type; formats the author, date, and tags.|"),
("| img\t| featureImages中的某个值\t| 文章特征图，推荐使用图床(腾讯云、七牛云、又拍云等)来做图片的路径.如: http://xxx.com/xxx.jpg| ", "| img\t| a value in featureImages\t| Featured image; using an image host (Tencent Cloud, Qiniu, Upyun, etc.) for the image path is recommended, e.g. http://xxx.com/xxx.jpg| "),
("| top\t| true\t| 推荐文章（文章是否置顶），如果 top 值为 true，则会作为首页推荐文章| ", "| top\t| true\t| Featured article (pinned or not); if true, shown as a homepage recommendation| "),
("| cover\t| false\t| v1.0.2版本新增，表示该文章是否需要加入到首页轮播封面中| ", "| cover\t| false\t| New in v1.0.2: whether the article is added to the homepage carousel covers| "),
("| coverImg\t| 无\t| v1.0.2版本新增，表示该文章在首页轮播封面需要显示的图片路径，如果没有，则默认使用文章的特色图片| ", "| coverImg\t| none\t| New in v1.0.2: the image path shown in the homepage carousel cover; falls back to the featured image if unset| "),
("| password\t| 无\t| 文章阅读密码，如果要对文章设置阅读验证密码的话，就可以设置 password 的值，该值必须是用 SHA256 加密后的密码，防止被他人识破。前提是在主题的 config.yml 中激活了 verifyPassword 选项| ", "| password\t| none\t| Article reading password; if set, it must be a SHA256-hashed value to avoid being guessed. Requires the verifyPassword option enabled in the theme's config.yml| "),
("| toc\t| true\t| 是否开启 TOC，可以针对某篇文章单独关闭 TOC 的功能。前提是在主题的 config.yml 中激活了 toc 选项| ", "| toc\t| true\t| Whether TOC is enabled; can be disabled per article. Requires the toc option enabled in the theme's config.yml| "),
("| mathjax\t| false\t| 是否开启数学公式支持 ，本文章是否开启 mathjax，且需要在主题的 _config.yml 文件中也需要开启才行| ", "| mathjax\t| false\t| Whether math formula support is enabled for this article; must also be enabled in the theme's _config.yml| "),
("| summary\t| 无\t| 文章摘要，自定义的文章摘要内容，如果这个属性有值，文章卡片摘要就显示这段文字，否则程序会自动截取文章的部分内容作为摘要| ", "| summary\t| none\t| Article summary; if set, the card shows this text, otherwise the program auto-truncates content as the summary| "),
("| categories\t| 无\t| 文章分类，本主题的分类表示宏观上大的分类，只建议一篇文章一个分类| ", "| categories\t| none\t| Article categories; this theme treats them as broad top-level groups, one per article is recommended| "),
("| tags\t| 无\t| 文章标签，一篇文章可以多个标签| ", "| tags\t| none\t| Article tags; an article can have multiple tags| "),
("| reprintPolicy\t| cc_by\t| 文章转载规则， 可以是 cc_by, cc_by_nd, cc_by_sa, cc_by_nc, cc_by_nc_nd, cc_by_nc_sa, cc0, noreprint 或 pay 中的一个| ", "| reprintPolicy\t| cc_by\t| Reprint policy; one of cc_by, cc_by_nd, cc_by_sa, cc_by_nc, cc_by_nc_nd, cc_by_nc_sa, cc0, noreprint, or pay| "),
("### yaml语法", "### yaml Syntax"),
("Markdown 文件头部定义有个front matter部分，这部分内容使用yaml语法。", "The front matter section at the top of a Markdown file uses yaml syntax."),
("**简单的yaml语法**", "**Simple yaml syntax**"),
("YAML 中有 3 种数据类型——对象/字典、数组和纯量，其中纯量中又包含了字符串、整数、浮点数、布尔值、空值、时间和日期。", "YAML has 3 data types: objects/mappings, arrays, and scalars; scalars include strings, integers, floats, booleans, nulls, times, and dates."),
("> YAML 支持编写注释，使用 # 表示行注释，直到行末尾都是注释内容，类似于 Python 语法中的行注释。YAML 是大小写敏感的，在编写时要注意大小写。", "> YAML supports comments: `#` starts a line comment that runs to the end of the line, like line comments in Python. YAML is case-sensitive, so mind your casing."),
("基本由`键`和`值`构成。`键`，必须是由 `a-zA-Z0-9_` 这些`英文+数字+下划线`构成，不要用中文。`值`，可以用各种字符串，中文也可以。", "It basically consists of `keys` and `values`. A `key` must consist of `a-zA-Z0-9_` (letters + digits + underscore), not Chinese characters. A `value` can be any string, including Chinese."),
("YAML 中的对象（mapping）类似于 Python 中的字典，它是一个由 key 和 value 组成的键值对。其中 key 可以是字符串、整数、浮点数，value 可以是 YAML 中的任意数据类型。", "An object (mapping) in YAML is like a dictionary in Python: key-value pairs. Keys can be strings, integers, or floats; values can be any YAML data type."),
("书写对象时，key 不需要加双引号，且 key 后面紧跟英文冒号，冒号后面必须接一个空格。", "When writing an object, keys need no double quotes; a key is followed directly by an English colon, and the colon must be followed by a space."),
("`键-值对`(key-value)，如，", "`key-value pairs`, e.g.,"),
("`键-列表值`，缩进为2个空格，同层级的字段数据是左侧对齐的。如果列表值比较简单，可以将列表值放在方`[]`中间。如，", "`key-list value`: indented by 2 spaces, with same-level fields left-aligned. If the list is simple, it can be written inside square brackets `[]`. E.g.,"),
("`键-字典`，子元素进行缩进，或构成嵌套。多个`键值对`，就是`字典`。如，", "`key-dictionary`: child elements are indented or nested. Multiple `key-value pairs` form a `dictionary`. E.g.,"),
("**字符串**", "**Strings**"),
("YAML 中单行字符串的 3 种基本写法如下所示。用单引号或者双引号包裹，也可以直接写字符串内容，无须引号包裹。", "The 3 basic ways to write single-line strings in YAML are shown below: wrapped in single or double quotes, or written directly without quotes."),
("在一些特殊的场景中，如字符串中涉及多行，可以考虑使用 `>` 或者 `|`。比如，", "In special cases such as multi-line strings, consider using `>` or `|`. For example,"),
("**日期与时间**", "**Dates and Times**"),
("日期类 date 是精确到天，时间类 datetime 是精确到微秒，二者的书写格式必须遵循 ISO 8601 标准。", "`date` is precise to the day and `datetime` to the microsecond; both must follow the ISO 8601 standard."),
("YAML 中日期与时间的写法如下所示。", "Dates and times in YAML are written as follows."),
("> 更多Yaml语法，参考下面链接。", "> For more yaml syntax, see the links below."),
("> [Yaml官网](https://yaml.org/)", "> [Yaml official site](https://yaml.org/)"),
("> [Yaml官方文档 - 规范1.2.2](https://yaml.org/spec/1.2.2/)", "> [Yaml official documentation - spec 1.2.2](https://yaml.org/spec/1.2.2/)"),
("> [YAML入门教程](https://www.runoob.com/w3cnote/yaml-intro.html)", "> [YAML getting started tutorial](https://www.runoob.com/w3cnote/yaml-intro.html)"),
("### css语法", "### CSS Syntax"),
("css语法支持对某个MD文件部分内容的颜色、线条等格式进行修饰。因为MD文件会被转为HTML页面，所以支持CSS语法修饰内容样式。", "CSS syntax can decorate parts of an MD file (colors, borders, etc.). Because an MD file is converted to an HTML page, CSS can style the content."),
("在MD文件前面部分或者文件后面加入CSS样式定义。<br>", "Add CSS style definitions at the beginning or end of the MD file.<br>"),
("每一条样式类型的定义，都要加`.page `，这样就只影响自己内容的局限部分，以避免影响整个页面其他部分。<br>", "Every style rule should be prefixed with `.page ` so it only affects the scoped part of your content, avoiding side effects on the rest of the page.<br>"),
("比如，将文件内表格左边加空白，使表格整体向右偏移20px个像素。鼠标经过表格某行时给它着色，鼠标移走后取消着色。", "For example, add left padding to a table so it shifts right by 20px; color a table row on hover and remove the color when the mouse leaves."),
("> 注：", "> Note:"),
("表格的标签名为 `table`，表格的行的标签为`tr`，表格的格子的标签为`td` ，", "The tag for tables is `table`, for table rows `tr`, and for table cells `td`,"),
("6个级别标题的标签为 `h1`, `h2`, `h3`, `h4`, `h5`, `h6` ，", "the tags for the 6 heading levels are `h1`, `h2`, `h3`, `h4`, `h5`, `h6`,"),
("代码和关键字的标签为 `code`，围栏的标签为 `pre` 或 `pre code` ，", "the tag for code and keywords is `code`, and for fenced blocks `pre` or `pre code`,"),
("加粗的标签为 `strong` ，或 `b` ，", "bold uses `strong` or `b`,"),
("斜体的标签为 `em` ，", "italic uses `em`,"),
("链接的标签为 `a` ，", "links use `a`,"),
("图片链接的标签为 `img` ，", "image links use `img`,"),
("分割线的标签为 `hr` ，", "horizontal rules use `hr`,"),
("段落的标签为 `p` ，", "paragraphs use `p`,"),
("无序列表的标签为 `ul` ， 每一个列表行的表签 `li` ，", "unordered lists use `ul`, with each item `li`,"),
("有序列表的标签为 `ol` ， 每一个列表行的表签 `li` ，", "ordered lists use `ol`, with each item `li`,"),
("引用的标签为 `blockquote` ，", "blockquotes use `blockquote`,"),
("highlight的代码块的标签为 `pre code`，它的最外层className为 `hljs`，行号的className为 `hljs-ln-numbers` 。另外，因为支持行号，所以代码块里面部分也包含 `table`, `tr`, `td` 等标签。", "highlighted code blocks use `pre code`, with the outer className `hljs` and the line numbers className `hljs-ln-numbers`. Since line numbers are supported, code blocks also contain `table`, `tr`, `td` tags."),
("svg图的外层标签为 `svg` 。", "SVG figures use the outer tag `svg`."),
("更多请参考HTML文档。", "For more, refer to the HTML documentation."),
("如果想加一个空白行，直接用标签 <code>&lt;br&gt;</code> 。", "To add a blank line, use the tag <code>&lt;br&gt;</code>."),
("如果有多个部分有相同的标签，但只想对其中一个的样式进行修饰，怎么办？", "What if multiple parts share the same tag but you only want to style one of them?"),
("我们可以定义一个样式，增加一个对标签 `<tag class=\"c1\">` 和 </tag>，将要修饰的内容放在这两个标签之间，并给样式类型起个名字 `c1`。", "Define a style: wrap the content to style with a pair of `<tag class=\"c1\">` and `</tag>` tags, and name the style class `c1`."),
("这样，在样式定义中，可以使用 `.page .c1 tr:hover`，表示在 类型 `page` 标签下的 类型 `c1` 下的 表格的行 `tr`的鼠标经过`hover`的样式定义，改变它的颜色。", "Then in the style definition you can use `.page .c1 tr:hover`, which defines the hover style of table rows `tr` under the `page` class and the `c1` class, changing their color."),
("下面举个例子。将选定的一个表格定义放在`tag`标签内，`<tag class=\"c1\">` 和 </tag>之间，前后都加一行空行。然后我们在md文件后面加`<style>...</style>`，在里面定义一个新的样式 `c1`，将表格向右偏移50个像素50px，表格表单头背景色改为翠绿色，并且鼠标经过表格行时改变背景色为品粉色。", "Here is an example: put a table inside `<tag class=\"c1\">` and `</tag>` with a blank line before and after. Then add `<style>...</style>` at the end of the MD file defining a new style `c1` that shifts the table right by 50px, sets the header background to jade green, and changes the row background to pink on hover."),
("另外，增加一个`tag`标签，将代码块放在`<tag class=\"c2\">` 和 </tag>之间，前后都加一行空行。然后我们在md文件后面加`<style>...</style>`，在里面定义一个新的样式 `c2`，改变代码块标签 `pre code`的背景色为翠绿色，再改变代码块的行号颜色为浅蓝色。", "Also, wrap a code block with `<tag class=\"c2\">` and `</tag>` with a blank line before and after, then add `<style>...</style>` at the end of the MD file defining a new style `c2` that sets the `pre code` background to jade green and the line numbers to light blue."),
("这两处改动，都不会影响到前面其它部分的样式，其它部分内容的样式还保持原样。代码关键字带有颜色，是因为自动判断内容为`html`语言，自动被`highlight JS`语法高亮了。", "Neither change affects the styles of other parts; everything else keeps its original style. The colored keywords appear because the content is auto-detected as `html` and highlighted by `highlight.js`."),
("这个样式类名可以随便定义，`字母+数字`的组合，也可以包含中短线`-`，比如前面定义的样式名`c1`和`c2`，在`<style>`里用样式类名时，前面要多加一个点`.`，这表示它是样式类名或className ，它是网页 CSS 选择器的常见的一种选择器。更多请参考Web编程语言HTML和CSS文档。", "Style class names are arbitrary: `letters+digits` combinations, possibly with hyphens `-`, like `c1` and `c2` above. In `<style>`, prefix a class name with a dot `.` to indicate a class name (className), a common CSS selector. For more, refer to the HTML and CSS documentation."),
("这个标签和样式尽量少用，非不得已时，简单使用一些。如果一个MD文件里使用太多样式定义，就会让MD文件失去了简单易读的特性，变成了另类的HTML网页编程了。", "Use these tags and styles sparingly, and keep them simple unless necessary. Too many style definitions make an MD file lose its simplicity and readability, turning it into HTML programming."),
("<p style=\"font-size:1.6rem;font-weight:bold;color:#000;\">tag 测试</p><br>", "<p style=\"font-size:1.6rem;font-weight:bold;color:#000;\">tag test</p><br>"),
("<p><strong>要点</strong></p>", "<p><strong>Key points</strong></p>"),
("<p>表格</p>", "<p>Table</p>"),
("<th>名字</th>", "<th>Name</th>"),
("<th>内容</th>", "<th>Content</th>"),
("<td>这是一个测试</td>", "<td>This is a test</td>"),
]
